
//! Autogenerated weights for `pallet_kitties`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-09-02, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ganzzi-Bravo-15-B5DD`, CPU: `AMD Ryzen 7 5800H with Radeon Graphics`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/debug/node-template
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_kitties
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// pallets/kitties/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_kitties`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_kitties::WeightInfo for WeightInfo<T> {
	/// Storage: KittiesModule Kitties (r:1 w:1)
	/// Proof Skipped: KittiesModule Kitties (max_values: None, max_size: None, mode: Measured)
	/// Storage: KittiesModule KittyId (r:1 w:1)
	/// Proof Skipped: KittiesModule KittyId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: KittiesModule KittiesOwned (r:1 w:1)
	/// Proof Skipped: KittiesModule KittiesOwned (max_values: None, max_size: None, mode: Measured)
	fn create_kitty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3`
		//  Estimated: `3468`
		// Minimum execution time: 219_240_000 picoseconds.
		Weight::from_parts(227_901_000, 0)
			.saturating_add(Weight::from_parts(0, 3468))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}
